// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqzrndjkuyclzjghxxfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxenJuZGprdXljbHpqZ2h4eGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMTM1NDEsImV4cCI6MjA3ODg4OTU0MX0.46voYI3dcT8Qx5O55AlgGEM2YvJ7L2uX5c1x-P9JjCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});